title: Site

columns:
  - width: 1/1
    sections:
      contentPages:
        type: pages
        headline: Deine Portfolios & Seiten
        layout: list
        sortable: true
        status: listed
        create:
          - default
        image:
          query: page.images.first
          cover: true
        templates:
          - default
          - home
          - about
          - contact
