title: Site

columns:
  - width: 1/1
    sections:
      contentPages:
        type: pages
        headline: Deine Portfolios & Seiten
        query: site.children.listed.sortBy("num", "asc")
        layout: list
        sortable: true
        create:
          - default
        empty: Noch keine Inhaltsseiten vorhanden.
        image:
          query: page.images.first
          cover: true
        templates:
          - default
          - home
          - about
          - contact
